"""
Do not run this until you have tmp folder generated by running run.sh
"""

import praw
import pprint
import sys
import math

username = sys.argv[1]
user_agent = "Karma breakdown for" + username
r = praw.Reddit(user_agent=user_agent)
user = r.get_redditor(username)
gen=user.get_submitted()
karma_by_subreddit={}
highestscore=0
highest=''
count=0
try:
	for thing in gen:
		count+=thing.score
except:
	pass
# pprint.pprint(karma_by_subreddit)
# print(thing.title)
score = 1.0
if count<10:
	score=1.0
else:
	score=math.log10(count)

with open("tmp/user_reddit.score", "w") as out:
	out.write(str(score))

	